app/models.py
from app import db, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def current_user(user_id):
    return User.query.get(user_id)


books_in_users = db.Table("books_users", 
    db.Column('user_id', db.Integer, db.ForeignKey('users.id'), nullable=False),
    db.Column('book_id', db.Integer, db.ForeignKey('books.id'), nullable=False),
) 


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(84), nullable=False)
    email = db.Column(db.String(84), nullable=False, unique=True, index=True)
    password = db.Column(db.String(255), nullable=False)
    profile = db.relationship('Profile', backref='user', uselist=False)
    books = db.relationship("Book", secondary=books_in_users, lazy=True,
        backref='users'
    )

    def __str__(self):
        return self.name

class Profile(db.Model):
    __tablename__ = "profiles"
    id = db.Column(db.Integer, primary_key=True)
    photo = db.Column(db.Unicode(124), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))


    def __str__(self):
        return self.name


class Book(db.Model):
    __tablename__ = "books"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(125), nullable=False)


    def __str__(self):
        return self.name

app/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import (BooleanField, PasswordField, StringField,
                            SubmitField, SelectField)
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Email, Length
from app.models import Book


class LoginForm(FlaskForm):
    email = EmailField("Email", validators=[
        Email()
    ])
    password = PasswordField("Senha", validators=[
        Length(3, 6, "O campo deve conter entre 3 á 6 caracters.")
    ])
    remember = BooleanField("Permanecer Conectado")
    submit = SubmitField("Logar")

class RegisterForm(FlaskForm):
    name = StringField("Nome Completo", validators=[
        DataRequired("o campo é obrigatório")
    ])
    email = EmailField("Email", validators=[
        Email()
    ])
    password = PasswordField("Senha", validators=[
        Length(3, 6, "O campo deve conter entre 3 á 6 caracters.")
    ])
    submit = SubmitField("Cadastrar")


class BookForm(FlaskForm):
    name = StringField("Nome do livro", validators=[
        DataRequired("o campo é obrigatório")
    ])
    submit = SubmitField("Salvar")


class UserBookForm(FlaskForm):
    book = SelectField("Livro", coerce=int)
    submit = SubmitField("Salvar")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.book.choices = [ 
            (book.id, book.name) for book in Book.query.all()
        ]

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_bootstrap import Bootstrap

db = SQLAlchemy()
login_manager = LoginManager()
bootstrap = Bootstrap()

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = 'secret'
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///app.db"
    app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    db.init_app(app)
    login_manager.init_app(app)
    bootstrap.init_app(app)

    from app import routes
    routes.init_app(app)

    return app

app/book/__init__.py
from flask import Blueprint

book = Blueprint("book", __name__)

from . import views

app/book/views.py
from flask import flash, redirect, render_template, url_for
from flask_login import current_user

from app import db
from app.forms import BookForm, UserBookForm
from app.models import Book

from . import book


@book.route("/book/add", methods=["GET", "POST"])
def book_add():
    form = BookForm()

    if form.validate_on_submit():
        book = Book()
        book.name = form.name.data

        db.session.add(book)
        db.session.commit()

        flash("Livro cadastrado com sucesso", "success")
        return redirect(url_for(".book_add"))
    return render_template("book/add.html", form=form)

@book.route("/user/<int:id>/add-book",  methods=["GET", "POST"])
def user_add_book(id):
    form = UserBookForm()

    if form.validate_on_submit():
        book = Book.query.get(form.book.data)
        current_user.books.append(book)

        db.session.add(current_user)
        db.session.commit()

        flash("Livro cadastrado com sucesso!", "success")
        return redirect(url_for(".user_add_book", id=current_user.id))

    return render_template("book/user_add_book.html", form=form)

app/routes.py
from app.auth import auth as auth_blueprint
from app.book import book as book_blueprint
from app.user import user as user_blueprint


def init_app(app):
    app.register_blueprint(auth_blueprint)
    app.register_blueprint(book_blueprint)
    app.register_blueprint(user_blueprint)

app/user/__init__.py
from flask import Blueprint

user = Blueprint("user", __name__)

from . import views

app/user/views.py
from flask import redirect, render_template, url_for
from flask_login import login_required

from app import db
from app.models import User

from . import user


@user.route("/")
def index():
    users = User.query.all() # Select * from users; 
    return render_template("users.html", users=users)

@user.route("/user/<int:id>")
@login_required
def unique(id):
    user = User.query.get(id)
    return render_template("user.html", user=user)

@user.route("/user/delete/<int:id>")
def delete(id):
    user = User.query.filter_by(id=id).first()
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for(".index"))

app/templates/base.html
<!doctype html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Gerenciamento de Usuários</title>
  
  {% block styles %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    {{ bootstrap.load_css() }}
  {% endblock styles %}
</head>

<body>
  {% include 'nav.html' %}

  <div class="container">
    {% block content %} {% endblock %}
  </div>

  {% block scripts %}
    {{ bootstrap.load_js() }}
  {% endblock %}
</body>

</html>

app/templates/book/add.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}
  {% include 'components/notification.html' %}
  {{ render_form(form) }}
{% endblock %}

app/templates/book/user_add_book.html
{% extends 'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}
  {% include 'components/notification.html' %}
  {{ render_form(form) }}
{% endblock %}

app/templates/components/notification.html
{% with notifications = get_flashed_messages(with_categories=True) %}
  {% if notifications %}
    {% for category, notification in notifications %}
      <div class="alert alert-{{category}} text-center">
          {{ notification }}
      </div>
    {% endfor %}
  {% endif %}
{% endwith %}

app/templates/login.html
{% extends  'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}
  {% include 'components/notification.html' %}
  {{render_form(form) }}
{% endblock %}

app/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{{ url_for('user.index') }}">Users</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarNav"
    aria-controls="navbarNav"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      {% if not current_user.is_authenticated %}
      <li class="nav-item">
        <a href="{{ url_for('auth.register') }}">Registrar</a>
      </li>
      <li class="nav-item">
        <a href="{{ url_for('auth.login') }}">Login</a>
      </li>
      {% else %}
      <li class="nav-item">
        <a href="{{ url_for('book.book_add') }}">Add Livros</a>
      </li>
      <li class="nav-item">
        <a href="{{ url_for('auth.logout') }}">Sair</a>
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

app/templates/register.html
{% extends  'base.html' %}

{% from 'bootstrap/form.html' import render_form %}

{% block content %}
  {% include 'components/notification.html' %}
  {{render_form(form) }}
{% endblock %}

app/templates/user.html
{% extends 'base.html' %} {% block content %}

<div class="mt-5">
  <a href="{{ url_for('user.index') }}" class="btn btn-info">
    <i class="fa fa-arrow-left" aria-hidden="true"></i>
    Voltar
  </a>
  <a
    href="{{ url_for('book.user_add_book', id=user.id) }}"
    class="btn btn-success"
  >
    <i class="fa fa-plus" aria-hidden="true"></i>
    Adicionar Livro
  </a>

  <table class="table table-striped mt-3">
    <tbody>
      <tr>
        <td>
          {{ user.id }}
        </td>
        <td>
          {{ user.name }}
        </td>
        <td>
          {{ user.email }}
        </td>
        <td>
          {{ user.profile.photo }}
        </td>
        <td>
          <a
            class="btn btn-danger btn-sm"
            href="{{ url_for('user.delete', id=user.id) }}"
          >
            <i class="fa fa-trash" aria-hidden="true"></i>
          </a>
        </td>
      </tr>
    </tbody>
  </table>

  <h2 class="text-muted">Books:</h2>

  <ul class="list-group list-group-flush mt-5">
    {% for book in user.books %}
    <li class="list-group-item">
      {{ book.name }}
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

app/templates/users.html
{% extends 'base.html' %} {% block content %} {% for user in users %}
<ul class="list-group list-group-flush">
  <li class="list-group-item">
    <a href="{{ url_for('user.unique', id=user.id) }}">{{ user.name }}</a>
  </li>
</ul>
{% endfor %} {% endblock %}